### ISSUE TITLE
Additional profile of Token Exchange

### ISSUE THREAD

**Issue by PieterKas** [oauth-wg/oauth-identity-chaining#31]
Comment from Kelly:

A.2.(A) Maybe we should cover this step (“The resource server of Domain A requests a token for the protected resource in Domain B from the authorization server in Domain A”)

**Comment by PieterKas** [comment]
Could this be the same as for the token exchange between the client and the authorization server in Domain A?

**Comment by kburgin3** [comment]
I'm now happy with the current text. Closing the issue

**Comment by kburgin3** [comment]
Current text is sufficient. Saying the first request in the protocol is out of scope is fine
