### ISSUE TITLE
Consider limiting token formats to JWT

### ISSUE THREAD

**Issue by PieterKas** [oauth-wg/oauth-identity-chaining#45]
Feedback from Brian Campbell

Conceptually having "flexibility for authorization servers to change format and content" sounds nice but I can't help but wonder if that flexibility is actually useful and if this document wouldn't be better served and more straightforward using just JWT authz grants from 7523 (rather than being abstract about using 7521 and the very brief mention of SAML w/out a 7522 ref).

**Comment by aaronpk** [comment]
I agree that limiting the authorization grant format to JWT is useful. In fact you've almost already done that by adding the `aud` validation to the processing rules here: https://www.ietf.org/archive/id/draft-schwenkschuster-oauth-identity-chaining-00.html#section-2.5.2

**Comment by PieterKas** [comment]
As discussed in the meeting with the editors and Aaron, we will make the use of JWT explicit.

**Comment by bc-pi** [comment]
PR #72 limits authorization grant format to RFC7523 JWT
