### ISSUE TITLE
example response missing issued_token_type

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-identity-chaining#60]
issued_token_type (a required parameter of a token exchange response https://www.rfc-editor.org/rfc/rfc8693#name-successful-response) is missing from the example response at https://www.ietf.org/archive/id/draft-schwenkschuster-oauth-identity-chaining-00.html#name-token-exchange-response

**Comment by PieterKas** [comment]
@arndt-s can you prepare a PR with an updated example?

**Comment by bc-pi** [comment]
example would be fixed by PR #72
