### ISSUE TITLE
Change spec name to focus on Authz

### ISSUE THREAD

**Issue by PieterKas** [oauth-wg/oauth-identity-chaining#67]
Change name to focus on authorization (e.g. cross-domain authorization). Purpose of renaming is to create clarity that this is a mechanism for cross domain authz and that identity flows with the authorization. Add text to make it clear how identity chaining is achieved as a result of using this spec (the idea that the identity is following the authorization).

**Comment by aaronpk** [comment]
My suggestion: "OAuth Cross-Domain Authorization Framework"

It focuses on the cross-domain authorization aspect, and also makes it clear this is a framework that will need to be profiled to be implemented.

**Comment by bc-pi** [comment]
Some discussion has happened elsewhere (email and webex) with apparent consensus on “OAuth Identity and Authorization Chaining Across Domains” as the proposed name.
