### ISSUE TITLE
How does the AS know it should generate a JWT Authorization Grant formatted token?

### ISSUE THREAD

**Issue by gffletch** [oauth-wg/oauth-identity-chaining#84]
In reading through section 2.3.1 it's unclear to me how the AS knows it should be generating a token for the purposes of chaining to a new domain other than the specification of the audience/resource. 

Are we sure that this is sufficient given the other profiles of token exchange that exist? Could there be cases where the AS is generating a token for the AS in domain B and the desired response token is NOT a JWT Authorization Grant formatted token?

**Comment by bc-pi** [comment]
I think audience/resource will be sufficient for the majority of cases. And ([soon more allowed](https://github.com/oauth-wg/oauth-identity-chaining/pull/83))requested_token_type  can be used to differentiate, if needed.

**Comment by aaronpk** [comment]
We had the same problem with our implementation, and are using the `requested_token_type` parameter to indicate that this is a cross-domain authorization JWT instead of other uses of token exchange.

**Comment by bc-pi** [comment]
https://github.com/oauth-wg/oauth-identity-chaining/pull/83 was merged
